"""Added new column for remained contract's amount

Revision ID: 02046775e512
Revises: 6f69f84a5d62
Create Date: 2024-08-15 16:49:11.550023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02046775e512'
down_revision = '6f69f84a5d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remained_amount', sa.DECIMAL(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('remained_amount')

    # ### end Alembic commands ###
