"""Added adv payer column in contracts table

Revision ID: 03db6dea2c5e
Revises: ddb728949de3
Create Date: 2024-07-18 14:42:19.626734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03db6dea2c5e'
down_revision = 'ddb728949de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }

    with op.batch_alter_table('contracts', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('adv_payer', sa.BOOLEAN(), nullable=False, default=False))
        batch_op.drop_constraint("fk_contracts_company_id_companies", type_='foreignkey')
        batch_op.create_foreign_key("fk_contracts_company_id_companies", 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint("fk_contracts_company_id_companies", type_='foreignkey')
        batch_op.create_foreign_key("fk_contracts_company_id_companies", 'companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('adv_payer')

    # ### end Alembic commands ###
