"""update category nullable to true

Revision ID: 299f47ecb3e1
Revises: 819345c31ddf
Create Date: 2024-05-01 15:42:47.986485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299f47ecb3e1'
down_revision = '819345c31ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###