"""empty message

Revision ID: 6f7d40d014ff
Revises: a8b8fedd4700
Create Date: 2024-04-29 10:51:59.466106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7d40d014ff'
down_revision = 'a8b8fedd4700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voens', schema=None) as batch_op:
        batch_op.drop_column('voen_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voen_name', sa.VARCHAR(length=16), nullable=False))

    # ### end Alembic commands ###
