"""change voen column to not nullable

Revision ID: 819345c31ddf
Revises: 
Create Date: 2024-05-01 12:16:15.971872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819345c31ddf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('voen',
               existing_type=sa.CHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('voen',
               existing_type=sa.CHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
