"""Adding a new end date in the contract table

Revision ID: 8ca77c120b4f
Revises: 02046775e512
Create Date: 2024-08-22 09:16:10.751016

"""
from alembic import op
import sqlalchemy as sa
from datetime import date

# revision identifiers, used by Alembic.
revision = '8ca77c120b4f'
down_revision = '02046775e512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=False, server_default=sa.func.current_date()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
