"""Remove category row and leave it for future app updates

Revision ID: 90ac10b70f30
Revises: 299f47ecb3e1
Create Date: 2024-05-21 17:17:07.808482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ac10b70f30'
down_revision = '299f47ecb3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voens')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=True))

    op.create_table('voens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('voen', sa.CHAR(length=12), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('voen')
    )
    # ### end Alembic commands ###
