"""New pdf files additions for the contract

Revision ID: 91cf43f70076
Revises: d60dd0ecb86e
Create Date: 2024-12-23 10:02:41.760956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cf43f70076'
down_revision = 'd60dd0ecb86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file_paths', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('pdf_file_paths')

    # ### end Alembic commands ###
