"""empty message

Revision ID: a8b8fedd4700
Revises: 
Create Date: 2024-04-29 10:17:06.414625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b8fedd4700'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_companies')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.DECIMAL(), nullable=False, server_default="0"))
        batch_op.alter_column('contract_number',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.CHAR(length=16),
               existing_nullable=False,
               server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('contract_number',
               existing_type=sa.CHAR(length=16),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('amount')

    # op.create_table('_alembic_tmp_companies',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('company_name', sa.CHAR(length=16), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
