"""empty message

Revision ID: aaf850387a86
Revises: 6f7d40d014ff
Create Date: 2024-04-29 10:54:14.943286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf850387a86'
down_revision = '6f7d40d014ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voens', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_voens_id", ['id'])
        batch_op.create_unique_constraint("unique_voen", ['voen'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
