"""Status column was added to the contracts table

Revision ID: d60dd0ecb86e
Revises: 06383cfd559e
Create Date: 2024-10-30 16:17:45.078973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'd60dd0ecb86e'
down_revision = '06383cfd559e'
branch_labels = None
depends_on = None

def column_exists(table_name: str, column_name: str, bind) -> bool:
    """
    :param table_name: str,
    :param column_name: str
    :param bind:
    :return: boolean
    """
    inspector = inspect(bind)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if not column_exists("contracts", "is_expired", bind):
        with op.batch_alter_table('contracts', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_expired', sa.BOOLEAN(), nullable=True))
        op.execute("UPDATE contracts SET is_expired=1")
        with op.batch_alter_table('contracts', schema=None) as batch_op:
            batch_op.alter_column('is_expired', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if column_exists("contracts", "is_expired", bind):
        with op.batch_alter_table('contracts', schema=None) as batch_op:
            batch_op.drop_column('is_expired')

    # ### end Alembic commands ###
