"""Add swifth, h/h, m/h and bank name columns to the companies column 

Revision ID: ddb728949de3
Revises: 3b0a11e708a1
Create Date: 2024-06-20 16:51:58.333712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb728949de3'
down_revision = '3b0a11e708a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('m_h', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('h_h', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('swift', sa.VARCHAR(length=11), nullable=True))
        batch_op.create_unique_constraint("uq_companies_swift", ['swift'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint("uq_companies_swift", type_='unique')
        batch_op.drop_column('swift')
        batch_op.drop_column('h_h')
        batch_op.drop_column('m_h')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
