"""Make username unique

Revision ID: de522f2f9e49
Revises: ed06b58b70d5
Create Date: 2024-08-30 14:23:15.342978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de522f2f9e49'
down_revision = 'ed06b58b70d5'
branch_labels = None
depends_on = None


def upgrade():

    naming_convention = {
        "uq": "uq_%(table_name)s_%(column_0_label)s",
    }
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_users_username", ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_username", type_='unique')

    # ### end Alembic commands ###
