"""Change the CHAR to the VARCHAR

Revision ID: ed06b58b70d5
Revises: 8ca77c120b4f
Create Date: 2024-08-30 12:21:10.686337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed06b58b70d5'
down_revision = '8ca77c120b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.CHAR(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               type_=sa.CHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
